# pages/urls.py

from django.urls import path
from .views import (HomePageView,
                    Choir2024View, 
                    InMyLifetimeView,
                    JHFChoirView,
                    JHFCharityConcertsView,
                    JHFCharityConcerts2018View,
                    ForThoseWhoLove,
                    ChineseNewYearView,
                    ChineseNewYear2023View,
                    ChineseNewYear2024View,
                    ### Health ####
                    MedicineSeriesView,
                    HealthTalksView,
                    BeautyCareView,
                    PhysicalCareAndRehabitationView,
                    NewHealthIdeasView,
                    PhysicalConditioningView,
                    PhysicalConditioningAView,
                    CosmetologyView,
                    MoxibustionView,
                    WetView,
                    ColdView,
                    HayFeverView,
                    ScarView,
                    AlzheimerView,
                    BadTemperView,
                    LoseWeightView,
                    HyperthermiaView,
                    DeficiencyView,
                    SleepView,
                    ImmuneSystemView,
                    GuaShaTherapyView,
                    FastingView,
                    Covid19View,
                    ConstipateView,
                    HealthPorridgeView,
                    NourishYourHeartView,
                    ChineseFoodTherapeuticsView,
                    ReduceWeightView,
                    RinsingRicesForYourBeautyView,
                    ### Culture ###
                    ColumnbyLingyaoWuView,
                    ConfusionaboutTimeView,
                    WeWillBeOlderTomorrowView,
                    AddMoreHumortoYourLifeView,
                    JHFCultureTalksView,
                    EstatePlanningView,
                    ShadowPlayView,
                    HappyLivingHomeView,
                    TeaCultureView,
                    GetCloserView,
                    JHFActivitiesView,
                    RealEstateView,
                    InvestinahouseView,
                    RespecttheElderlyDinnerView,
                    CulturearoundtheWorldView,
                    DieAtTheAgeOfView,
                    TheHiddenMeaningsofYinYangView,
                    ShaoKongchuanBelCantoView,
                    SuiHaopingView,
                    SuiHaopingconcertView,
                    SuiHaopingToastmastersView,
                    befriendwithyourbody1View,
                    TakeCareOfYourHeartView,
                    ChineseMedicineDietTherapyView,
                    LowBackPainView,
                    MissionsView,
                    ContactUsView,
                    )

urlpatterns= [
    path ("", HomePageView.as_view(), name="home"),
    path ("choir2024/", Choir2024View.as_view(), name="choir2024"),   
    path ("inmylifetime/",InMyLifetimeView.as_view(), name="inmylifetime"),
    path ("jhfchoir/", JHFChoirView.as_view(),name="jhfchoir"),
    path ("jhfcharityconcerts/",JHFCharityConcertsView.as_view(), name="jhfcharityconcerts"),
    path ("jhfcharityconcerts2018/",JHFCharityConcerts2018View.as_view(), name="JHFCharityConcerts2018View"),
    path ("forthosewholove/",ForThoseWhoLove.as_view(), name="forthosewholove"),
    path ("chinesenewyear/", ChineseNewYearView.as_view(), name="chinesenewyear"),
    path ("chinesenewyear2023/",ChineseNewYear2023View.as_view(), name="chinesenewyear2023"),
    path ("chinesenewyear2024/",ChineseNewYear2024View.as_view(), name="chinesenewyear2024"),
    # *** Health #####
    path ("medicineseries/",MedicineSeriesView.as_view(),name="medicineseries"),
    path ("healthtalks/",HealthTalksView.as_view(),name="healthtalks"),
    path ("beautycare/",BeautyCareView.as_view(),name="beautycare"),
    path ("physicalcareandrehabitation/", PhysicalCareAndRehabitationView.as_view(), name="physicalcareandrehabitation"),
    path ("newhealthideas/", NewHealthIdeasView.as_view(), name="newhealthideas"),
    path ("physicalconditioning/",PhysicalConditioningView.as_view(), name="physicalconditioning"),
    path ("physicalconditioninga/",PhysicalConditioningAView.as_view(), name="physicalconditioninga"),
    path ("Cosmetology/",CosmetologyView.as_view(), name="Cosmetology"),
    path ("Moxibustion/",MoxibustionView.as_view(), name="Moxibustion"),
    path ("wet/", WetView.as_view(), name='wet'),
    path ("cold/", ColdView.as_view(),name="cold"),
    path ("hayfever/", HayFeverView.as_view(), name="hayfever"),
    path ("scar/", ScarView.as_view(), name="scar"),
    path ("alzheimer/",AlzheimerView.as_view(),name="alzheimer"),
    path ("badtemper/", BadTemperView.as_view(), name='badtemper'),
    path ("loseweight/", LoseWeightView.as_view(), name="loseweight"),
    path ("hyperthermia/", HyperthermiaView.as_view(), name="hyperthermia"),
    path ("deficiency/", DeficiencyView.as_view(),name="deficiency"),
    path ("sleep/", SleepView.as_view(), name="sleep"),
    path ("immunesystem/", ImmuneSystemView.as_view(), name="immunesystem"),
    path ("guashatherapy/", GuaShaTherapyView.as_view(), name="guashatherapy"),
    path ("fasting/", FastingView.as_view(), name="fasting"),
    path ("covid19/",Covid19View.as_view(), name="covid19"),
    path ("befriendwithyourbody1/", befriendwithyourbody1View.as_view(), name="befriendwithyourbody1"),
    path ("TakeCareOfYourHeart", TakeCareOfYourHeartView.as_view(), name="TakeCareOfYourHeart"),
    path ("ChineseMedicineDietTherapy", ChineseMedicineDietTherapyView.as_view(), name="ChineseMedicineDietTherapy"),
    path ("LowBackPain.html", LowBackPainView.as_view(), name="LowBackPain"),

    path ("constipate/", ConstipateView.as_view(), name="constipate"),
    path ("healthporridge/", HealthPorridgeView.as_view(), name="healthporridge"),
    path ("NourishYourHeart/",NourishYourHeartView.as_view(), name="NourishYourHeart"),
    path ("ChineseFoodTherapeutics/", ChineseFoodTherapeuticsView.as_view(), name="ChineseFoodTherapeutics"),
    path ("ReduceWeight/",ReduceWeightView.as_view(), name="ReduceWeight"),
    path ("RinsingRicesForYourBeauty/",RinsingRicesForYourBeautyView.as_view(), name="RinsingRicesForYourBeauty"),
    #### Culture ####
    path ("ColumnbyLingyaoWu/", ColumnbyLingyaoWuView.as_view(), name="ColumnbyLingyaoWu"),
    path ("ConfusionaboutTime/", ConfusionaboutTimeView.as_view(), name="ConfusionaboutTime"),
    path ("WeWillBeOlderTomorrow/",WeWillBeOlderTomorrowView.as_view(), name="WeWillBeOlderTomorrow"),
    path ("AddMoreHumortoYourLife/", AddMoreHumortoYourLifeView.as_view(), name="AddMoreHumortoYourLife"),
    path ("JHFCultureTalks/",JHFCultureTalksView.as_view(), name="JHFCultureTalks"),
    path ("EstatePlanning/",EstatePlanningView.as_view(), name="EstatePlanning"),
    path ("ShadowPlay/",ShadowPlayView.as_view(),name="ShadowPlay"),
    path ("HappyLivingHome/",HappyLivingHomeView.as_view(), name="HappyLivingHome"),
    path ("TeaCulture/",TeaCultureView.as_view(),name="TeaCulture"),
    path ("GetCloser/",GetCloserView.as_view(),name="GetCloser"),
    ### Activities ######
    path ("JHFActivities/",JHFActivitiesView.as_view(), name="JHFActivities"),
    path ("RealEstate/", RealEstateView.as_view(), name="RealEstate"),
    path ("Investinahouse/", InvestinahouseView.as_view(), name="Investinahouse"),
    path ("RespecttheElderlyDinner/", RespecttheElderlyDinnerView.as_view(), name="RespecttheElderlyDinner"),
    path ("CulturearoundtheWorld/", CulturearoundtheWorldView.as_view(), name="CulturearoundtheWorld"),
    path ("DieAtTheAgeOf/", DieAtTheAgeOfView.as_view(), name="DieAtTheAgeOf"),
    path ("TheHiddenMeaningsofYinYang/", TheHiddenMeaningsofYinYangView.as_view(), name="TheHiddenMeaningsofYinYang"),
    path ("ShaoKongchuanBelCanto/", ShaoKongchuanBelCantoView.as_view(), name="ShaoKongchuanBelCanto"),
    path ("suihaoping/", SuiHaopingView.as_view(), name="suihaoping"),
    path ("suihaopingconcert/", SuiHaopingconcertView.as_view(), name="suihaopingconcert"),
    path ("suihaopingtoastmasters/",SuiHaopingToastmastersView.as_view(), name="suihaopingtoastmasters"),
    path ("Missions/", MissionsView.as_view(), name="Missions"),
    path ("ContactUs", ContactUsView.as_view(), name="ContactUs"),
]